- name: Build and push web server image to Azure Container Registry
  hosts: localhost
  tasks:
    - name: Build the web server image with Podman
      command: podman build -t practicasegunda.azurecr.io/servidor_web:latest /home/azureuser/Practica2/podman

    - name: Log in to Azure Container Registry
      command: podman login --username "{{ azure_username }}" --password "{{ azure_password }}" practicasegunda.azurecr.io
      vars:
        azure_username: "PracticaSegunda"
        azure_password: "SZbVgVduwYdwCS+govJUYBKNd1HFILcfq5YFfut7hB+ACRD/6WFs"

    - name: Push the web server image to Azure Container Registry
      command: podman push practicasegunda.azurecr.io/servidor_web:latest
